function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

export const preguntas = shuffleArray([
  { texto: "¿Quién mató a Héctor durante la Guerra de Troya?", opciones: ["Aquiles","Paris","Ulises","Menelao"], respuesta: "Aquiles" },
  { texto: "¿Quién ayudó a los griegos en la Guerra de Troya creando el caballo de madera?", opciones: ["Ulises","Aquiles","Héctor","Agamenón"], respuesta: "Ulises" },
  { texto: "¿Quién era el dios del Sol en la mitología griega?", opciones: ["Apolo","Zeus","Hades","Hermes"], respuesta: "Apolo" },
  { texto: "¿Quién era considerado el rey de los dioses griegos?", opciones: ["Zeus","Hades","Poseidón","Cronos"], respuesta: "Zeus" },
  { texto: "¿Quién era el dios griego del inframundo?", opciones: ["Hades","Poseidón","Zeus","Ares"], respuesta: "Hades" },
  { texto: "¿Cuál era el arma principal de Zeus?", opciones: ["El rayo","El tridente","La lira","El casco de invisibilidad"], respuesta: "El rayo" },
  { texto: "¿Quién era el dios griego de la guerra?", opciones: ["Ares","Hermes","Apolo","Dionisio"], respuesta: "Ares" },
  { texto: "¿Quién era considerado el dios de la sabiduría?", opciones: ["Atenea","Hefesto","Apolo","Hermes"], respuesta: "Atenea" },
  { texto: "¿Quién ayudó a los griegos con la Guerra de Troya proporcionando armas y estrategia?", opciones: ["Atenea","Hefesto","Apolo","Hermes"], respuesta: "Atenea" },
  { texto: "¿Quién creó a los humanos según la mitología griega?", opciones: ["Prometeo","Zeus","Athena","Hefesto"], respuesta: "Prometeo" },
  { texto: "¿Qué regalo recibió Pandora?", opciones: ["La caja de todos los males","El rayo","El tridente","El casco de invisibilidad"], respuesta: "La caja de todos los males" },
  { texto: "¿Quién fue condenado a rodar una piedra eternamente?", opciones: ["Sísifo","Tántalo","Prometeo","Atlas"], respuesta: "Sísifo" },
  { texto: "¿Quién era la diosa de la caza en Grecia?", opciones: ["Artemisa","Atenea","Hera","Afrodita"], respuesta: "Artemisa" },
  { texto: "¿Quién era el dios griego de la música y la profecía?", opciones: ["Apolo","Hermes","Dionisio","Ares"], respuesta: "Apolo" },
  { texto: "¿Quién era el dios griego del amor?", opciones: ["Eros","Ares","Hermes","Dionisio"], respuesta: "Eros" },
  { texto: "¿Quién era el dios griego del comercio y el robo?", opciones: ["Hermes","Apolo","Ares","Dionisio"], respuesta: "Hermes" },
  { texto: "¿Quién era la diosa griega del matrimonio?", opciones: ["Hera","Afrodita","Artemisa","Atenea"], respuesta: "Hera" },
  { texto: "¿Quién era el dios nórdico del engaño?", opciones: ["Loki","Odin","Thor","Tyr"], respuesta: "Loki" },
  { texto: "¿Quién era el dios nórdico del trueno?", opciones: ["Thor","Odin","Loki","Balder"], respuesta: "Thor" },
  { texto: "¿Qué objeto posee Thor para lanzar rayos?", opciones: ["Mjolnir","Gungnir","Brisingamen","Skidbladnir"], respuesta: "Mjolnir" },
  { texto: "¿Quién era la madre de Thor según la mitología nórdica?", opciones: ["Jörd","Frigg","Freya","Sif"], respuesta: "Jörd" },
  { texto: "¿Quién era el dios nórdico de la sabiduría?", opciones: ["Odin","Thor","Loki","Tyr"], respuesta: "Odin" },
  { texto: "¿Qué dios nórdico tenía dos cuervos que lo acompañaban?", opciones: ["Odin","Thor","Loki","Frey"], respuesta: "Odin" },
  { texto: "¿Quién era la diosa romana del hogar y la familia?", opciones: ["Vesta","Juno","Minerva","Venus"], respuesta: "Vesta" },
  { texto: "¿Quién era el dios egipcio del sol?", opciones: ["Ra","Osiris","Horus","Anubis"], respuesta: "Ra" },
  { texto: "¿Cuál era el dios griego del sol?", opciones: ["Apolo","Helios","Ares","Dionisio"], respuesta: "Apolo" },
  { texto: "¿Quién era la diosa egipcia del amor y la belleza?", opciones: ["Isis","Hathor","Nephthys","Sekhmet"], respuesta: "Hathor" },
  { texto: "¿Quién era el dios del cielo y del clima en Egipto?", opciones: ["Ra","Osiris","Anubis","Horus"], respuesta: "Ra" },
  { texto: "¿Quién era el dios de la medicina segun los romanos?", opciones: ["Asclepio","Apolo","Hermes","Dionisio"], respuesta: "Asclepio" },
  { texto: "¿Dónde vivía Osiris según la mitología egipcia?", opciones: ["En el Duat","En la Tierra","En el Nilo","En el cielo"], respuesta: "En el Duat" },
  { texto: "¿Quién juzgaba el alma de los muertos en Egipto?", opciones: ["Anubis","Osiris","Thoth","Ra"], respuesta: "Anubis" },
  { texto: "¿Quién creó a Pandora según la mitología griega?", opciones: ["Hephaestus","Athena","Zeus","Hermes"], respuesta: "Hephaestus" },
  { texto: "¿Quién era la madre de Heracles?", opciones: ["Alcmena","Hera","Deméter","Atenea"], respuesta: "Alcmena" },
  { texto: "¿Quién mató a Aquiles según algunas versiones del mito?", opciones: ["Paris","Héctor","Apolo","Menelao"], respuesta: "Paris" },
  { texto: "¿Quién fue la madre de Aquiles?", opciones: ["Tetis","Hera","Themis","Atenea"], respuesta: "Tetis" },
  { texto: "¿Quién era el dios de la curación y la luz en Egipto?", opciones: ["Horus","Ra","Thoth","Anubis"], respuesta: "Horus" },
  { texto: "¿Qué titán enseñó a los humanos las artes y ciencias?", opciones: ["Prometeo","Cronos","Atlas","Hiperión"], respuesta: "Prometeo" },
  { texto: "¿Quién era el dios de la guerra en Roma?", opciones: ["Marte","Ares","Júpiter","Mercurio"], respuesta: "Marte" },
  { texto: "¿Cuál era el dios griego del mar y los terremotos?", opciones: ["Poseidón","Zeus","Hades","Hermes"], respuesta: "Poseidón" },
  { texto: "¿Quién era el dios de los cielos y el trueno en Egipto?", opciones: ["Horus","Ra","Osiris","Anubis"], respuesta: "Horus" },
  { texto: "¿Cuál era el dios de los sueños en Grecia?", opciones: ["Morfeo","Hypnos","Hermes","Hades"], respuesta: "Morfeo" },
  { texto: "¿Quién era el dios griego de los caminos y mensajero de los dioses?", opciones: ["Hermes","Apolo","Ares","Dionisio"], respuesta: "Hermes" },
  { texto: "¿Quién era la diosa de la agricultura en Grecia?", opciones: ["Deméter","Hera","Atenea","Artemisa"], respuesta: "Deméter" },
  { texto: "¿Quién era el dios egipcio de la escritura y la sabiduría?", opciones: ["Thoth","Ra","Anubis","Osiris"], respuesta: "Thoth" },
  { texto: "¿Cuál era el animal sagrado de Bastet?", opciones: ["Gato","Perro","Toro","Halcón"], respuesta: "Gato" },
  { texto: "¿Qué dios nórdico renació tras Ragnarök?", opciones: ["Balder","Odin","Thor","Loki"], respuesta: "Balder" },
  { texto: "¿Quién era la madre de los dioses del Olimpo?", opciones: ["Rea","Hera","Deméter","Gea"], respuesta: "Rea" },
  { texto: "¿Cuál era el hijo de Cronos que sobrevivió y derrocó a su padre?", opciones: ["Zeus","Hades","Poseidón","Heracles"], respuesta: "Zeus" },
  { texto: "¿Quién era conocido como el dios de la luz y del arte en Grecia?", opciones: ["Apolo","Hermes","Dionisio","Hefesto"], respuesta: "Apolo" },
  { texto: "¿Quién fue castigado a cargar el mundo sobre sus hombros?", opciones: ["Atlas","Prometeo","Sisifo","Tántalo"], respuesta: "Atlas" },
  { texto: "¿Qué regalo recibió Pandora?", opciones: ["La caja de todos los males","El rayo","El tridente","El casco de invisibilidad"], respuesta: "La caja de todos los males" },
  { texto: "¿Qué animal era sagrado para Sobek?", opciones: ["Cocodrilo","Gato","Halcón","Toro"], respuesta: "Cocodrilo" },
  { texto: "¿Dónde se encuentra el Valhalla según la mitología nórdica?", opciones: ["En Asgard","En Midgard","En Jötunheim","En Helheim"], respuesta: "En Asgard" },
  { texto: "¿Qué dios nórdico tenía dos cuervos que lo acompañaban?", opciones: ["Odin","Thor","Loki","Frey"], respuesta: "Odin" },
  { texto: "¿Quién ayudó a los griegos con la Guerra de Troya proporcionando armas y estrategia?", opciones: ["Atenea","Hefesto","Apolo","Hermes"], respuesta: "Atenea" },
  { texto: "¿Quién era la princesa troyana conocida por su belleza que causó la Guerra de Troya?", opciones: ["Helena","Andrómaca","Cassandra","Hécuba"], respuesta: "Helena" },
  { texto: "¿Quién era el segundo guerrero más grande de los aqueos en la Guerra de Troya?", opciones: ["Aquiles","Héctor","Ayax","Agamenón"], respuesta: "Ayax" },
  { texto: "¿Quién mató a Héctor durante la Guerra de Troya?", opciones: ["Aquiles","Paris","Ulises","Menelao"], respuesta: "Aquiles" },
  { texto: "¿Quién era el dios romano equivalente a Hermes?", opciones: ["Mercurio","Marte","Júpiter","Neptuno"], respuesta: "Mercurio" },
  { texto: "¿Cómo era conocido Hermes en Roma?", opciones: ["Mercurio","Marte","Júpiter","Neptuno"], respuesta: "Mercurio" },
  { texto: "¿Qué diosa nació de la cabeza de Zeus?", opciones: ["Atenea","Afrodita","Artemisa","Hera"], respuesta: "Atenea" },
  { texto: "¿Quién era la madre de Heracles?", opciones: ["Alcmena","Hera","Deméter","Atenea"], respuesta: "Alcmena" },
  { texto: "¿Quién fue condenado a rodar una piedra eternamente?", opciones: ["Sísifo","Tántalo","Prometeo","Atlas"], respuesta: "Sísifo" },
  { texto: "¿Qué titán fue encadenado bajo el Tártaro?", opciones: ["Cronos","Oceanus","Hyperion","Atlas"], respuesta: "Cronos" },
  { texto: "¿Quién intentó devorar a sus hijos por miedo a ser derrocado?", opciones: ["Cronos","Urano","Zeus","Hades"], respuesta: "Cronos" },
  { texto: "¿Quién era el dios del vino en Grecia?", opciones: ["Dionisio","Apolo","Hermes","Ares"], respuesta: "Dionisio" },
  { texto: "¿Quién era el dios del cielo y del clima en Egipto?", opciones: ["Ra","Osiris","Anubis","Horus"], respuesta: "Ra" },
  { texto: "¿Cuál era el animal sagrado de Horus?", opciones: ["Halcón","Gato","Toro","Cocodrilo"], respuesta: "Halcón" },
  { texto: "¿Quién era la diosa egipcia del amor y la belleza?", opciones: ["Isis","Hathor","Nephthys","Sekhmet"], respuesta: "Hathor" },
  { texto: "¿Quién era el dios de la muerte y la momificación en Egipto?", opciones: ["Anubis","Osiris","Thoth","Sobek"], respuesta: "Anubis" },
  { texto: "¿Dónde vivía Osiris según la mitología egipcia?", opciones: ["En el Duat","En la Tierra","En el Nilo","En el cielo"], respuesta: "En el Duat" },
  { texto: "¿Quién juzgaba el alma de los muertos en Egipto?", opciones: ["Anubis","Osiris","Thoth","Ra"], respuesta: "Anubis" },
  { texto: "¿Cuál era el dios nórdico del engaño?", opciones: ["Loki","Odin","Thor","Tyr"], respuesta: "Loki" },
  { texto: "¿Qué objeto posee Thor?", opciones: ["Mjolnir","Gungnir","Brisingamen","Skidbladnir"], respuesta: "Mjolnir" },
  { texto: "¿Quién era el dios nórdico de la justicia y la guerra?", opciones: ["Tyr","Odin","Thor","Loki"], respuesta: "Tyr" },
  { texto: "¿Quién era la madre de Thor según la mitología nórdica?", opciones: ["Jörd","Frigg","Freya","Sif"], respuesta: "Jörd" },
  { texto: "¿Qué mato a Odin durante el Ragnarök?", opciones: ["Loki","Ymir","Fenrir","Jörmungandr"], respuesta: "Fenrir" },
  { texto: "¿Quién mato a Baldur?", opciones: ["Loki","Skadi","Heimdall","Frigg"], respuesta: "Loki" },
  { texto: "¿Quién fue el dios griego del amor?", opciones: ["Eros","Ares","Hermes","Dionisio"], respuesta: "Eros" },
  { texto: "¿Quién era la diosa de la caza en Grecia?", opciones: ["Artemisa","Atenea","Hera","Afrodita"], respuesta: "Artemisa" },
  { texto: "¿Quién era el dios de la música y la profecía?", opciones: ["Apolo","Hermes","Dionisio","Ares"], respuesta: "Apolo" },
  { texto: "¿Quién creó a los humanos según la mitología griega?", opciones: ["Prometeo","Zeus","Athena","Hefesto"], respuesta: "Prometeo" },
  { texto: "¿Quién fue condenado a que un águila le devorara el hígado cada día?", opciones: ["Prometeo","Sísifo","Tántalo","Atlas"], respuesta: "Prometeo" },
  { texto: "¿Quién era el dios griego de la medicina?", opciones: ["Asclepio","Apolo","Hermes","Dionisio"], respuesta: "Asclepio" },
  { texto: "¿Quién era el dios del inframundo egipcio?", opciones: ["Osiris","Anubis","Ra","Horus"], respuesta: "Osiris" },
  { texto: "¿Quién ayudó a los griegos en la Guerra de Troya creando el caballo de madera?", opciones: ["Ulises","Aquiles","Héctor","Agamenón"], respuesta: "Ulises" },
  { texto: "¿Quién mató a Aquiles según algunas versiones del mito?", opciones: ["Paris","Héctor","Apolo","Menelao"], respuesta: "Paris" },
  { texto: "¿Quién fue la madre de Aquiles?", opciones: ["Tetis","Hera","Themis","Atenea"], respuesta: "Tetis" },
  { texto: "¿Quién era el dios de la curación y la luz en Egipto?", opciones: ["Horus","Ra","Thoth","Anubis"], respuesta: "Horus" },
  { texto: "¿Qué titán enseñó a los humanos las artes y ciencias?", opciones: ["Prometeo","Cronos","Atlas","Hiperión"], respuesta: "Prometeo" },
  { texto: "¿Quién era la diosa romana del hogar y la familia?", opciones: ["Vesta","Juno","Minerva","Venus"], respuesta: "Vesta" },
  { texto: "¿Cuál era el dios griego del mar y los terremotos?", opciones: ["Poseidón","Zeus","Hades","Hermes"], respuesta: "Poseidón" },
  { texto: "¿Quién era el dios de la guerra en Roma?", opciones: ["Marte","Ares","Júpiter","Mercurio"], respuesta: "Marte" },
  { texto: "¿Quién era el dios de los cielos y el trueno en Egipto?", opciones: ["Horus","Ra","Osiris","Anubis"], respuesta: "Horus" },
  { texto: "¿Cuál era el dios de los sueños en Grecia?", opciones: ["Morfeo","Apolo","Hermes","Hades"], respuesta: "Morfeo" },
  { texto: "¿Quién era el dios griego de los caminos y mensajero de los dioses?", opciones: ["Hermes","Apolo","Ares","Dionisio"], respuesta: "Hermes" },
  { texto: "¿Quién era la diosa de la agricultura en Grecia?", opciones: ["Deméter","Hera","Atenea","Artemisa"], respuesta: "Deméter" },
  { texto: "¿Quién era el dios egipcio de la escritura y la sabiduría?", opciones: ["Thoth","Ra","Anubis","Osiris"], respuesta: "Thoth" },
  { texto: "¿Cuál era el animal sagrado de Bastet?", opciones: ["Gato","Perro","Toro","Halcón"], respuesta: "Gato" },
  { texto: "¿Qué dios nórdico renació tras Ragnarök?", opciones: ["Balder","Odin","Thor","Loki"], respuesta: "Baldr" },
  { texto: "¿Qué titán fue condenado a sostener el cielo?", opciones: ["Atlas","Prometeo","Cronos","Hiperión"], respuesta: "Atlas" },
  { texto: "¿Quién era el dios griego del comercio y el robo?", opciones: ["Hermes","Apolo","Ares","Dionisio"], respuesta: "Hermes" },
  { texto: "¿Quién era la diosa griega del matrimonio?", opciones: ["Hera","Afrodita","Artemisa","Atenea"], respuesta: "Hera" },
  { texto: "¿Quién era el dios nórdico de la muerte?", opciones: ["Hel","Odin","Tyr","Thor"], respuesta: "Hel" },
  { texto: "¿Quién era la diosa nórdica del amor y la fertilidad?", opciones: ["Freya","Frigg","Sif","Skadi"], respuesta: "Freya" },
  { texto: "¿Quién era el dios griego del sol?", opciones: ["Apolo","Hermes","Helios","Dionisio"], respuesta: "Apolo" },
  { texto: "¿Quién era la representacion de la luna?", opciones: ["Selene","Artemisa","Rea","Afrodita"], respuesta: "Selene" },
  { texto: "¿Quién ayudo a Zeus para que Cronos vomitara a sus hermanos?", opciones: ["Metis","Rea","Gea","Urano"], respuesta: "Metis" },
  { texto: "¿Con que objeto castraron a Urano?", opciones: ["Hoz","Espada","Hacha","Lanza"], respuesta: "Hoz" },
  { texto: "¿Quién creó a Pandora según la mitología griega?", opciones: ["Hephaestus","Athena","Zeus","Hermes"], respuesta: "Hephaestus" },
  { texto: "¿Quién era el dios griego de los mares y los terremotos?", opciones: ["Poseidón","Zeus","Hades","Ares"], respuesta: "Poseidón" },
  { texto: "¿Quién era la diosa griega de la belleza?", opciones: ["Afrodita","Hera","Artemisa","Atenea"], respuesta: "Afrodita" },
  { texto: "¿Quién era el dios egipcio del sol?", opciones: ["Ra","Osiris","Horus","Anubis"], respuesta: "Ra" },
  { texto: "¿Qué dios nórdico podía ver todo lo que sucedía?", opciones: ["Odin","Thor","Loki","Tyr"], respuesta: "Odin" },
  { texto: "¿Cuantas 'Caras' o formas tenía el dios Ra en base al momento del día?", opciones: ["1","8","3","9"], respuesta: "3" },
  { texto: "¿Qué Dios trajo devuelta al Ojo de Ra despues de haber discutido con este?", opciones: ["Anubis","Isis","Toth","Osiris"], respuesta: "Toth" },
  { texto: "¿Quién era el dios de la Riqueza?", opciones: ["Hades","Perséfone","Telémaco","Calypso"], respuesta: "Hades" },
  { texto: "¿Qué deidad Rapto a Perséfone?", opciones: ["Hades","Demeter","Zeus","Poseidon"], respuesta: "Hades" },
  { texto: "Qué comio Perséfone en el Inframundo?", opciones: ["Granada","Uvas","Olivas","Melocotón"], respuesta: "Granada" },
  { texto: "Qué regalo Atenea en la prueba por Atenas contra Poseidón?", opciones: ["Olivo","Fuente de Agua","Armas","Telares"], respuesta: "Olivo" },
  { texto: "¿A qué deidad Pertenecía el templo de Efeso?", opciones: ["Artemisa","Atenea","Zeus","Marte"], respuesta: "Artemisa" },
  { texto: "¿Cuál Diosa no tuvo hijos?", opciones: ["Demeter","Perséfone","Afrodita","Artemisa"], respuesta: "Artemisa" },
  { texto: "¿Cuántos años tardo Ulises en volver a Itaca?", opciones: ["30","12","15","20"], respuesta: "20" },
  { texto: "¿De que color eran las velas del barco de Teseo al volver a casa?", opciones: ["Rojas","Blancas","Negras","Azules"], respuesta: "Negras" },
  { texto: "¿Quién es el portero del Olimpo?", opciones: ["San Pedro","Heracles","Jesus","Isis"], respuesta: "Heracles" },
  { texto: "¿Cómo se llamaba el barco de Jasón?", opciones: ["Perla Negra","Argo","Going Merry","Poseidón"], respuesta: "Argo" },
  { texto: "¿Quién era el protector de los Jovenes?", opciones: ["Apolo","Zeus","Hades","Poseidon"], respuesta: "Apolo" },
  { texto: "¿Quién era la guardiana de las Doncellas?", opciones: ["Atenea","Artemisa","Hera","Afrodita"], respuesta: "Artemisa" },
  { texto: "¿Quién era la guardiana de las Doncellas?", opciones: ["Atenea","Artemisa","Hera","Afrodita"], respuesta: "Artemisa" },
  { texto: "¿Cuantas copias hace Draupnir?", opciones: ["7","5","8","6"], respuesta: "8" },
  { texto: "¿Cuanto tiempo tarda Draupnir en hacer copias?", opciones: ["7 noches","5 noches","8 noches","9 noches"], respuesta: "9 noches" },
  { texto: "¿Quien derrota al Gigante Talos?", opciones: ["Heracles","Medea","Jason","Ulises"], respuesta: "Medea" },
  { texto: "¿Quien es la Reina de las Amazonas?", opciones: ["Hera","Atenea","Medea","Hipolita"], respuesta: "Hipolita" },
  { texto: "Cuál es la musa de la poseía epica?", opciones: ["Caliope","Clío ","Euterpe","Erato"], respuesta: "Caliope" },
  { texto: "Cuál es la musa de la historia?", opciones: ["Polimnia","Clío","Polimnia","Terpsícore"], respuesta: "Clío" },
  { texto: "Cuál es la musa de la danza?", opciones: ["Urania","Terpsícore","Euterpe","Talía"], respuesta: "Terpsícore" },
  { texto: "Quien no forma parte del Juicio de Paris?", opciones: ["Afrodita","Psique ","Atenea ","Hera "], respuesta: "Psique" },
  { texto: "Cuál fue el noveno trabajo de Heracles?", opciones: ["Matar al Leon de Nemea","Domar el toro de Creta","Limpiar los establos de Augías","Capturar a la cierva de Cerinea"], respuesta: "Domar el toro de Creta" },
  { texto: "Cuál fue el quinto trabajo de Heracles?", opciones: ["Domar a Cerbero","Robar el ganado de Gerión","Limpiar los establos de Augías","Capturar vivo al jabalí de Erimanto"], respuesta: "Limpiar los establos de Augías" },
  { texto: "Cuál fue el undecimo trabajo de Heracles?", opciones: ["Robar las manzanas doradas del jardín de las Hespérides","Capturar vivo al jabalí de Erimanto","Limpiar los establos de Augías","Expulsar a las aves del Estínfalo"], respuesta: "Robar las manzanas doradas del jardín de las Hespérides" },
  { texto: "Cuáles fueron los mortales que intentaron Raptar a Perséfone?", opciones: ["Teseo y Piritoo","Sisifo y Tántalo","Perseo y Heracles","Ulises y Polites Estínfalo"], respuesta: "Teseo y Piritoo" },
  { texto: "¿Quién creo la red de pesca?", opciones: ["Odín","Loki","Thor","Frygg"], respuesta: "Loki" },
  { texto: "¿Qué no pidio el gigante constructor por los muros de Asgard?", opciones: ["Sol","Luna","Riquezas","Freyja"], respuesta: "Riquezas" },
  { texto: "¿Quién era la Diosa de la Venganza y Guerra?", opciones: ["Sekmet","Isis","Neftis","But"], respuesta: "Sekmet" },
  { texto: "¿Qué objeto no le prestaron a Perseo?", opciones: ["Sandalias Aladas","Egida de Atenea","Bolsa ","Lanza de Ares"], respuesta: "Lanza de Ares" },

].map(p => ({
  ...p,
  opciones: shuffleArray([...p.opciones]) 
})));
